name: API
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - scikit-learn
  - pytest
  - requests
  - fastapi=0.112.2
  - uvicorn
  - gunicorn=22.0.0
  - dvc=3.58.0
